In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
arr1.shape

(5,)

In [7]:
arr1.reshape((5,1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
arr1.reshape([5,1])

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
arr=arr1.reshape((1,5))
type(arr)

numpy.ndarray

In [10]:
arr.shape

(1, 5)

In [11]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [12]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
arr.shape

(2, 5)

In [15]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [28]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
arr.shape

(2, 5)

In [30]:
arr.ndim

2

In [31]:
arr.size

10

In [32]:
arr.dtype

dtype('int32')

In [33]:
arr.itemsize

4

In [34]:
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])
a+b

array([11, 22, 33, 44, 55])

In [35]:
a-b

array([ -9, -18, -27, -36, -45])

In [36]:
a**b

array([          1,     1048576, -1010140999,           0,  1296002393])

In [37]:
a*b

array([ 10,  40,  90, 160, 250])

In [38]:
a/b

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [39]:
b/a

array([10., 10., 10., 10., 10.])

In [40]:
a//b

array([0, 0, 0, 0, 0])

In [41]:
#universal functions
a

array([1, 2, 3, 4, 5])

In [42]:
b

array([10, 20, 30, 40, 50])

In [43]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [44]:
np.sqrt(a+b)

array([3.31662479, 4.69041576, 5.74456265, 6.63324958, 7.41619849])

In [45]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [46]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [47]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [48]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [53]:
a=np.arange(1,13).reshape(3,4)

In [54]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
a[0][0]

1

In [58]:
print(a[1:,2:])

[[ 7  8]
 [11 12]]


In [59]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
a[1:,::]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
a[:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [64]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
print(a[1:,1:3])

[[ 6  7]
 [10 11]]


In [68]:
b=a.flatten()

In [69]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
a[0]=20000

In [72]:
a

array([[20000, 20000, 20000, 20000],
       [    5,     6,     7,     8],
       [    9,    10,    11,    12]])

In [73]:
a[:]=10000

In [74]:
a

array([[10000, 10000, 10000, 10000],
       [10000, 10000, 10000, 10000],
       [10000, 10000, 10000, 10000]])

In [76]:
#statistical concepts
#Normalization
# to have mean 0 and standard deviation of 1

In [77]:
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)
normalized_data=(data-mean)/std_dev
normalized_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [79]:
print(np.mean(data))
print(np.median(data))
print(np.var(data))
print(np.std(data))


3.0
3.0
2.0
1.4142135623730951


In [80]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [81]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [86]:
data[(data<5) &(data<8)]

array([1, 2, 3, 4])