In [4]:
import numpy as np
arr=np.random.randint(1,21,size=(5,5))

In [5]:
arr

array([[ 2, 15, 18, 20,  5],
       [12, 13, 18, 17, 14],
       [ 6, 20, 20, 11, 17],
       [19, 12, 12, 16, 20],
       [ 8, 14,  2,  9,  9]])

In [6]:
arr[0]

array([ 2, 15, 18, 20,  5])

In [9]:
arr[::][2:3]=1

In [10]:
arr

array([[ 2, 15,  1, 20,  5],
       [12, 13,  1, 17, 14],
       [ 1,  1,  1,  1,  1],
       [19, 12,  1, 16, 20],
       [ 8, 14,  1,  9,  9]])

In [12]:
arr=np.arange(1,17)

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [26]:
arr=arr.reshape(4,4)

In [27]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
for i in range(len(arr)):
    for j in range(len(arr)):
        if i==j:
            arr[i][j]=0

In [24]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
for i in range(len(arr)):
    for j in range(i,len(arr)):
        if i==j:
            arr[i][j]=0

In [32]:
arr

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [33]:
arr=np.arange(1,37).reshape(6,6)

In [34]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [35]:
arr[2:5,1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [39]:
arr=np.random.randint(1,11,size=(5,5))
arr

array([[10,  9,  6,  9,  7],
       [ 9, 10,  6,  2,  1],
       [ 3,  8, 10, 10,  7],
       [ 1,  3,  4, 10,  1],
       [ 9,  2,  5,  9,  5]])

In [46]:
print("Original Array")
print(arr) 
border_elements=np.concatenate([arr[0,::],arr[-1,::],arr[1:-1,0],arr[1:-1,-1]])
border_elements

Original Array
[[10  9  6  9  7]
 [ 9 10  6  2  1]
 [ 3  8 10 10  7]
 [ 1  3  4 10  1]
 [ 9  2  5  9  5]]


array([10,  9,  6,  9,  7,  9,  2,  5,  9,  5,  9,  3,  1,  1,  7,  1])

In [43]:
import numpy as np

# Create a 5x5 array with random integers between 1 and 20
array = np.random.randint(1, 21, size=(5, 5))
print("Original Array:")
print(array)

# Extract the border elements
border_elements = np.concatenate([array[0, :],        # top row
                                  array[-1, :],       # bottom row
                                  array[1:-1, 0],     # left column excluding corners
                                  array[1:-1, -1]])   # right column excluding corners

print("\nBorder Elements:")
print(border_elements)


Original Array:
[[ 4  3 15 20 19]
 [ 5 18 12 20 10]
 [10 11  3 11  4]
 [ 7 14 16 13 17]
 [ 5  2 18 10 10]]

Border Elements:
[ 4  3 15 20 19  5  2 18 10 10  5 10  7 10  4 17]


In [47]:
arr1=np.random.randint(1,10,size=(3,4))
arr2=np.random.randint(1,10,size=(3,4))

In [48]:
arr1

array([[6, 1, 3, 6],
       [4, 7, 6, 3],
       [3, 2, 6, 6]])

In [49]:
arr2

array([[1, 9, 4, 2],
       [9, 5, 7, 8],
       [6, 1, 5, 4]])

In [53]:
print("addition")
print(arr1+arr2)
print("Subraction")
print(arr1-arr2)
print("multiplication")
print(arr1*arr2) 
print("division")
print(arr1/arr2)

addition
[[ 7 10  7  8]
 [13 12 13 11]
 [ 9  3 11 10]]
Subraction
[[ 5 -8 -1  4]
 [-5  2 -1 -5]
 [-3  1  1  2]]
multiplication
[[ 6  9 12 12]
 [36 35 42 24]
 [18  2 30 24]]
division
[[6.         0.11111111 0.75       3.        ]
 [0.44444444 1.4        0.85714286 0.375     ]
 [0.5        2.         1.2        1.5       ]]


In [54]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
np.sum(arr,axis=0)

array([28, 32, 36, 40])

In [56]:
np.sum(arr,axis=1)

array([10, 26, 42, 58])

In [57]:
arr=np.random.randint(1,10,size=(5,5))

In [58]:
arr

array([[9, 7, 2, 4, 5],
       [6, 4, 5, 1, 7],
       [7, 8, 8, 6, 7],
       [6, 2, 4, 7, 6],
       [7, 1, 8, 3, 1]])

In [59]:
np.mean(arr)

5.24

In [60]:
np.median(arr)

6.0

In [61]:
np.std(arr)

2.387969849055888

In [62]:
np.var(arr)

5.7024

In [63]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
mean=np.mean(arr)
std=np.std(arr)
normalized_arr=(arr-mean)/std
normalized_arr

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [65]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
print("determinent",np.linalg.det(arr))
print("\n")
#print("Eigen Values and Eigen Vectors")
EigenValues,EigenVectors=np.linalg.eig(arr)
print("Eigenvalues",EigenValues,"\n")
print("EigenVectors",EigenVectors)
print("\n")
print("Inverse",np.linalg.inv(arr))

determinent -9.51619735392994e-16


Eigenvalues [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16] 

EigenVectors [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


Inverse [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [75]:
arr1=np.arange(1,7).reshape(2,3)
arr2=np.arange(1,7).reshape(2,3)

In [76]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.matmul(arr1,arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [74]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [79]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [81]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [82]:
arr=np.random.randint(1,10,size=(5,5))
arr

array([[3, 4, 3, 5, 2],
       [4, 8, 1, 7, 3],
       [9, 3, 9, 7, 1],
       [1, 7, 4, 6, 5],
       [5, 2, 1, 9, 5]])

In [83]:
arr.flatten()

array([3, 4, 3, 5, 2, 4, 8, 1, 7, 3, 9, 3, 9, 7, 1, 1, 7, 4, 6, 5, 5, 2,
       1, 9, 5])

In [84]:
arr

array([[3, 4, 3, 5, 2],
       [4, 8, 1, 7, 3],
       [9, 3, 9, 7, 1],
       [1, 7, 4, 6, 5],
       [5, 2, 1, 9, 5]])

In [85]:
arr=arr.flatten()

In [86]:
arr

array([3, 4, 3, 5, 2, 4, 8, 1, 7, 3, 9, 3, 9, 7, 1, 1, 7, 4, 6, 5, 5, 2,
       1, 9, 5])

In [87]:
arr=arr.reshape(5,5)

In [88]:
arr

array([[3, 4, 3, 5, 2],
       [4, 8, 1, 7, 3],
       [9, 3, 9, 7, 1],
       [1, 7, 4, 6, 5],
       [5, 2, 1, 9, 5]])

In [90]:
arr=np.random.randint(1,20,size=(4,4))
arr

array([[ 3,  3, 12, 16],
       [12, 10, 13, 13],
       [ 3, 10, 15,  4],
       [12, 11,  7, 12]])

In [92]:
mask=arr>=10
arr[arr>=10]

array([12, 16, 12, 10, 13, 13, 10, 15, 12, 11, 12])

In [ ]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

In [ ]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)